version: "3"
services:
  feedback-collector-ui:
    image: vijithaekanayake/feedback-web-ui
    restart: always
    build:
      context: ./feedback-collector-ui
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongo
      - feedback-collector

  feedback-collector:
    image: vijithaekanayake/feedback-collector
    container_name: feedback-collector-service
    restart: always
    build:
      context: ./feedback-collector/feedback-collector-service
      dockerfile: Dockerfile
    ports:
      - 8090:8090
    depends_on:
      - mongo
      - minio
    environment:
      - "FEEDBACK_APPLICATION_LOG_LEVEL=INFO"
    links:
      - fluentd-s3
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: feedbacks

  fluentd-s3:
    container_name: fluentd-s3
    image: govtechsg/fluentd-s3:fluentd-1.3.2_fluent-plugin-s3-latest
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf
    ports:
      - "24224:24224"
    depends_on:
      - minio

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017

  mongoexpress:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongo

  minio:
    image: minio/minio:RELEASE.2020-06-18T02-23-35Z
    ports:
      - "9000:9000"
    volumes:
      - ./test/.minio/data:/export
      - ./test/.minio/config:/root/.minio
    environment:
      - "MINIO_ACCESS_KEY=minio"
      - "MINIO_SECRET_KEY=minio123"
    command: server /export
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3